# A network of four nodes connected in a line that connects Alice to Bob, Bob to Charlie and Charlie to David.

qdevice_cfg: &qdevice_cfg
    num_qubits: 2
    # coherence times (The value 0 disables decoherence)
    T1: 500_000_000
    T2: 500_000_000
    
    # gate execution times
    init_time: 10_000
    single_qubit_gate_time: 10_000
    two_qubit_gate_time: 10_000
    measure_time: 10_000

    # noise model
    single_qubit_gate_depolar_prob: 0.5
    two_qubit_gate_depolar_prob: 0.5

stacks:
  - name: Alice
    qdevice_typ: generic
    qdevice_cfg:
      <<: *qdevice_cfg
  - name: Bob
    qdevice_typ: generic
    qdevice_cfg:
      <<: *qdevice_cfg
  - name: Charlie
    qdevice_typ: generic
    qdevice_cfg:
      <<: *qdevice_cfg
  - name: David
    qdevice_typ: generic
    qdevice_cfg:
      <<: *qdevice_cfg

link_cfg: &link_cfg
  # Fidelity between the EPR pair qubits
  fidelity: 0.97
  # Chance for each attempt at entanglement to succeed
  prob_success: 0.2
  # Distance between adjacent nodes
  length: 10

links:
  - stack1: Alice
    stack2: Bob
    typ: depolarise
    cfg:
      <<: *link_cfg
  - stack1: Bob
    stack2: Charlie
    typ: depolarise
    cfg:
      <<: *link_cfg
  - stack1: Charlie
    stack2: David
    typ: depolarise
    cfg:
      <<: *link_cfg


clinks:
  - stack1: Alice
    stack2: Bob
    typ: default
    cfg:
      length: 10

  - stack1: Bob
    stack2: Charlie
    typ: default
    cfg:
      length: 10

  - stack1: Charlie
    stack2: David
    typ: default
    cfg:
      length: 10
